In [5]:
import pandas as pd

In [6]:
#Read a .csv form a URL with Pandas

In [7]:
#Reading one csv file from internet
df_premier23 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2324/E0.csv')

In [8]:
#Rename cloumns
df_premier23.rename(columns={
    'FTHG':'home_goals',
    'FTAG': 'away_goals'
}, inplace=True)

In [9]:
df_premier23

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,...,2.99,-1.00,1.84,2.06,1.85,2.09,1.87,2.13,1.82,2.07
279,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,...,2.13,0.25,1.95,1.95,1.94,1.98,1.97,2.00,1.91,1.94
280,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,...,2.23,0.00,1.95,1.95,1.96,1.96,1.97,1.99,1.94,1.94
281,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,...,2.72,0.50,1.86,2.04,1.88,2.05,1.90,2.11,1.83,2.04
282,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,...,2.39,0.00,1.83,2.10,1.84,2.10,1.85,2.12,1.82,2.06